__title__ = 'frosta'
__version__ = '1.1'
__license__ = 'LGPL3'
__author__ = 'Tomas Feseker'
__copyright__ = 'TerraSense GmbH'
__contact__ = 'feseker@terrasense.de'
__url__ = 'https://terrasense.de'
__description__ = 'a user-friendly client to facilitate interaction with an OGC SensorThings API Server (e.g., FROST-Server)'
