__title__ = 'frosta'
__version__ = '1.0'
__license__ = 'LGPL3'
__author__ = 'Tomas Feseker'
__copyright__ = 'ahu GmbH'
__contact__ = 't.feseker@ahu.de'
__url__ = 'https://ahu.de'
__description__ = 'a user-friendly client to facilitate interaction with an OGC SensorThings API Server (e.g., FROST-Server)'
